### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by insolor** [dfint/installer#3]
- [x] Add basic description to README.md (#4) 
- [x] Add test building on pushes and pull requests (#12)
- [x] Add dependabot config (#6)
- [x] Setup syncronization of GUI localization with transifex: https://app.transifex.com/dwarf-fortress-translation/installer-3/dashboard/
